server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5435/${TM_DB:task_manager_db}
    username: ${TM_USER}
    password: ${TM_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500, expireAfterAccess=10m

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600

first-admin:
  firstname: ${INIT_ADMIN_FIRSTNAME}
  lastname: ${INIT_ADMIN_LASTNAME}
  email: ${INIT_ADMIN_EMAIL}
  password: ${INIT_ADMIN_PASSWORD}

logging:
  file:
    path: ${LOG_PATH}
    name: ${LOG_FILE}
  level:
    root: info
    sql: trace
    org:
      springframework:
        security: trace